package controlador;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.DatePicker;

public class alquilerController {
	@FXML
	private TextField txtNombre;
	@FXML
	private TextField txtApellido1;
	@FXML
	private TextField txtApellido2;
	@FXML
	private DatePicker dtFecha;
	@FXML
	private Button btnBoton;

	// Event Listener on Button[#btnBoton].onAction
	@FXML
	public void enviar(ActionEvent event) {
		// TODO Autogenerated
	}
}
